### ISSUE TITLE
Reach node responsible for a client using a special IP

### ISSUE THREAD

**Issue by tcatm** [tcatm/l3roamd#25]
Nodes could generate a special IP address generated using a clients MAC address (like: PREFIX::MAC), announce a local route and assign this address to `lo`. A node claiming a client would first look for a route to this special IP address and if it is present contact the node previously serving the client using this address to initiate a smooth handover.

Maybe use fec0::/10?

**Comment by bittorf** [comment]
please always drop a short message why you close issues (e.g. "implemented" or "bad idea" 8-)
