### ISSUE TITLE
please make cfg80211 dependency optional

### ISSUE THREAD

**Issue by christf** [tcatm/l3roamd#29]
when running l3roamd the kernel module cfg80211 must be loaded otherwise l3roamd exits with the message:
"nl80211 not found"

the error message seems to be originating from wifistations.c
 
  106         int nl80211_id = genl_ctrl_resolve(ctx->nl_sock, "nl80211");
  107         if (nl80211_id < 0) {
  108                 fprintf(stderr, "nl80211 not found.\n");
  109                 goto fail;
  110         }

should l3roamd really depend on cfg80211 even if the system that it runs on does not contain wifi hardware?

**Comment by christf** [comment]
well... loading cfg80211 solvees the issue - but maybe l3roamd should not depend on this on systems without wifi interface.

**Comment by matwei** [comment]
To confirm the problem you can create a file /etc/modprobe.d/cfg80211.conf containing this line:

    blacklist cfg80211

Then make sure with rmmod that the module is unloaded and start l3roamd:

    $ sudo src/l3roamd -i eth0
    Setting up icmp6 interface: 0
    nl80211 not found.
    Could not open nl80211 socket
